name: RAvatar
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - pytorch=1.10.1
  - pip
  - pip:
    - numpy==1.21.2
    - chumpy==0.70
    - scipy==1.9.0
    - open3d==0.15.2
    - trimesh==3.14.0
    - rtree==0.9.7
    - imageio==2.21.1
    - opencv-python==4.6.0.66
    - scikit-image==0.19.3
    - pymcubes==0.1.2
    - pymeshfix==0.16.1
    - pyyaml==6.0
    - tensorboardX==2.5.1
    - termcolor==2.0.1
    - tqdm==4.64.1
