task: 'geometry_rec'
gpus: [0]

parent_cfg: 'configs/geometry_base.yaml'

train_dataset_module: 'lib.datasets.syn_dataset'
train_dataset_path: 'lib/datasets/syn_dataset.py'
test_dataset_module: 'lib.datasets.syn_dataset'
test_dataset_path: 'lib/datasets/syn_dataset.py'

train_dataset:
    data_root: 'data/mixamo/ch21'
    human: 'ch21'
    ann_file: 'data/mixamo/ch21/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/mixamo/ch21'
    human: 'ch21'
    ann_file: 'data/mixamo/ch21/annots.npy'
    split: 'test'

test:
    frame_sampler_interval: 30

train:
    warm_up: True
    warm_up_iters: 20000
    fix_smpl_iters: 200000
    epoch: 400 

N_samples: 256
ratio: 0.5
training_view: [1, 4, 7, 9]
test_view: [0, 2, 5, 8]
num_train_frame: 100
num_eval_frame: 100
begin_ith_frame: 0
frame_interval: 1
smpl: 'smpl'
vertices: 'vertices'
params: 'params'
use_bigpose: True
big_box: True

mesh_cfg:
    begin_ith_frame: 0
    end_ith_frame: 300
    frame_interval: 1

    non_rigid_deform: False

    # out_type: 'deformed' 
    out_type: 'posed'
    # out_type: 'world'

    test:
        sampler: 'FrameSampler'
        frame_sampler_interval: 30

