task: 'geometry_rec'
gpus: [0]

parent_cfg: 'configs/geometry_base.yaml'

train_dataset:
    data_root: 'data/zju_mocap/CoreView_377'
    human: 'CoreView_377'
    ann_file: 'data/zju_mocap/CoreView_377/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/zju_mocap/CoreView_377'
    human: 'CoreView_377'
    ann_file: 'data/zju_mocap/CoreView_377/annots.npy'
    split: 'test'

test:
    frame_sampler_interval: 30

train:
    warm_up: True
    warm_up_iters: 20000
    fix_smpl_iters: 200000
    epoch: 400 

N_samples: 256
ratio: 0.5
training_view: [0, 6, 12, 18]
test_view: [9]
num_train_frame: 300
num_eval_frame: 1000
begin_ith_frame: 0
frame_interval: 1
smpl: 'new_smpl'
vertices: 'new_vertices'
params: 'new_params'
use_bigpose: True
big_box: True

mesh_cfg:

    # renderer_module: 'lib.networks.renderer.sdf_mesh_renderer_dataset'
    # renderer_path: 'lib/networks/renderer/sdf_mesh_renderer_dataset.py'

    test:
        sampler: 'FrameSampler'
        frame_sampler_interval: 30 # 1 # 
