task: 'material_rec'
gpus: [0]

parent_cfg: 'configs/material_base.yaml'

train_dataset:
    data_root: 'data/zju_mocap/CoreView_377'
    human: 'CoreView_377'
    ann_file: 'data/zju_mocap/CoreView_377/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/zju_mocap/CoreView_377'
    human: 'CoreView_377'
    ann_file: 'data/zju_mocap/CoreView_377/annots.npy'
    split: 'test'

geometry_model_path: 'data/trained_model/geometry_rec/geometry_zju_377'
lvis_model_path: 'data/trained_model/geometry_rec/lvis_zju_377'

novel_light_path: 'data/envmaps/studio'
novel_poses_path: 'data/pose_seq/gBR_sBM_cAll_d04_mBR0_ch01.npz'
novel_light: True

img_w: 1024
img_h: 1024

test:
    frame_sampler_interval: 30

train:
    epoch: 200 
    use_vis: True
    use_part_wise: True

N_samples: 256
ratio: 0.5
training_view: [0, 6, 12, 18]
test_view: [3]
num_train_frame: 300
num_eval_frame: 1000
begin_ith_frame: 0
frame_interval: 1
smpl: 'new_smpl'
vertices: 'new_vertices'
params: 'new_params'
use_bigpose: True
big_box: True

mesh_cfg:
    test:
        sampler: 'FrameSampler'
        frame_sampler_interval: 30 # 1 # 
