task: 'material_rec'
gpus: [0]

parent_cfg: 'configs/material_base.yaml'

train_dataset_module: 'lib.datasets.ps_dataset'
train_dataset_path: 'lib/datasets/ps_dataset.py'
test_dataset_module: 'lib.datasets.ps_dataset'
test_dataset_path: 'lib/datasets/ps_dataset.py'

train_dataset:
    data_root: 'data/people_snapshot/male-3-casual'
    human: 'male-3-casual'
    ann_file: 'data/people_snapshot/male-3-casual/params.npy'
    split: 'train'

test_dataset:
    data_root: 'data/people_snapshot/male-3-casual'
    human: 'male-3-casual'
    ann_file: 'data/people_snapshot/male-3-casual/params.npy'
    split: 'test'

smpl_model_path: './data/smplx/smpl/basicmodel_m_lbs_10_207_0_v1.1.0.pkl'

geometry_model_path: 'data/trained_model/geometry_rec/geometry_ps_m3c'
lvis_model_path: 'data/trained_model/geometry_rec/lvis_ps_m3c'

novel_light_path: 'data/envmaps/pine'
novel_poses_path: 'data/pose_seq/gLO_sBM_cAll_d14_mLO5_ch05.npz'
novel_light: False

img_w: 1080
img_h: 1080

test:
    frame_sampler_interval: 30

train:
    epoch: 200 
    use_vis: True
    use_part_wise: True

N_samples: 256
ratio: 0.5
training_view: [0]
test_view: [0]
num_train_frame: 300
num_eval_frame: 100
begin_ith_frame: 0
frame_interval: 1
smpl: 'smpl'
vertices: 'vertices'
params: 'params'
use_bigpose: True
big_box: True

mesh_cfg:
    test:
        sampler: 'FrameSampler'
        frame_sampler_interval: 30
