task: 'material_rec'
gpus: [0]

parent_cfg: 'configs/material_base.yaml'

train_dataset_module: 'lib.datasets.syn_dataset'
train_dataset_path: 'lib/datasets/syn_dataset.py'
test_dataset_module: 'lib.datasets.syn_dataset'
test_dataset_path: 'lib/datasets/syn_dataset.py'

train_dataset:
    data_root: 'data/h36m/S9/Posing'
    human: 'S9'
    ann_file: 'data/h36m/S9/Posing/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/h36m/S9/Posing'
    human: 'S9'
    ann_file: 'data/h36m/S9/Posing/annots.npy'
    split: 'test'

geometry_model_path: 'data/trained_model/geometry_rec/geometry_h36m_s9p'
lvis_model_path: 'data/trained_model/geometry_rec/lvis_h36m_s9p'

novel_light_path: 'data/envmaps/dawn'
novel_poses_path: 'data/pose_seq/gBR_sBM_cAll_d04_mBR0_ch01.npz'
novel_light: False

img_w: 1024
img_h: 1024

test:
    frame_sampler_interval: 30

train:
    epoch: 200 
    use_vis: True
    use_part_wise: True

N_samples: 256
ratio: 1.
training_view: [0, 1, 2]
test_view: [3]
num_train_frame: 250
num_eval_frame: 127
begin_ith_frame: 0
frame_interval: 5
smpl: 'new_smpl'
vertices: 'new_vertices'
params: 'new_params'
use_bigpose: True
big_box: True

mesh_cfg:
    test:
        sampler: 'FrameSampler'
        frame_sampler_interval: 30 # 1 # 
